language: node_js
node_js:
  - "4"
  - "5"
  - "iojs"
after_success:
  - ./node_modules/.bin/remap-istanbul --input coverage/coverage.json --type lcovonly --output lcov && ./node_modules/.bin/coveralls < lcov
